name: 'digital_lending_analytics'
version: '1.0.0'
config-version: 2
profile: 'rubyx_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  digital_lending_analytics:
    staging:
      +materialized: view
    marts:
      finance:
        +materialized: table
      risk:
        +materialized: table
      operations:
        +materialized: table
