version: 2

models:
  - name: stg_loans
    columns:
      - name: loan_id
        tests: [not_null, unique]
      - name: principal_usd
        tests: [not_null]
      - name: product_type
        tests:
          - accepted_values:
              values: [nano_loan, micro_loan, sme_loan, bnpl]

  - name: stg_repayments
    columns:
      - name: payment_id
        tests: [not_null, unique]
      - name: loan_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_loans')
              field: loan_id
